### ISSUE TITLE
NPE: Tesselating block model (1.15.2)

### ISSUE THREAD

**Issue by FSwordFoxA** [CJMinecraft01/DoubleSlabs#111]
Minecraft version: 1.15.2
Forge version: 31.2.36
Optifine version: 1.15.2_HD_U_G1_pre30
GPU: MSI Radeon RX 580 ARMOR OC (4GB)

I was placing down some polished stone slabs to extend a new bridge to an abandoned city (lost cities mod) when the game crashed to desktop.

The crash was consistent for that particular chunk in subsequent attempts to finish the bridge. The one time the crash didn't happen was when I had disabled Optifine, but that does not necessarily mean anything yet.

I did collect the crash report, and here it is. I also wonder if my java arguments might be messing with things a little.

---- Minecraft Crash Report ----
// Don't do that.

Time: 8/26/20 1:37 PM
Description: Tesselating block model

java.lang.NullPointerException: Tesselating block model
	at net.optifine.render.RenderEnv.isBreakingAnimation(RenderEnv.java:157) ~[?:?] {re:classloading}
	at net.optifine.model.BlockModelCustomizer.getRenderQuads(BlockModelCustomizer.java:54) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.BlockModelRenderer.renderModelSmooth(BlockModelRenderer.java:145) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.renderModelSmooth(ForgeBlockModelRenderer.java:89) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.BlockModelRenderer.renderModel(BlockModelRenderer.java:101) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.BlockRendererDispatcher.renderModel(BlockRendererDispatcher.java:82) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$ChunkRender$RebuildTask.func_228940_a_(ChunkRenderDispatcher.java:877) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$ChunkRender$RebuildTask.func_225618_a_(ChunkRenderDispatcher.java:711) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.lambda$runTask$1(ChunkRenderDispatcher.java:180) ~[?:?] {re:classloading,xf:OptiFine:default}
	at java.util.concurrent.CompletableFuture.uniCompose(Unknown Source) ~[?:1.8.0_211] {}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source) ~[?:1.8.0_211] {}
	at java.util.concurrent.CompletableFuture.uniComposeStage(Unknown Source) ~[?:1.8.0_211] {}
	at java.util.concurrent.CompletableFuture.thenCompose(Unknown Source) ~[?:1.8.0_211] {}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.func_228909_h_(ChunkRenderDispatcher.java:178) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.lambda$schedule$4(ChunkRenderDispatcher.java:252) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213148_e(SourceFile:83) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213145_a(SourceFile:123) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.run(SourceFile:91) ~[?:?] {re:classloading}
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source) ~[?:1.8.0_211] {}
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0_211] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) ~[?:1.8.0_211] {}
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:1.8.0_211] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:1.8.0_211] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.optifine.render.RenderEnv.isBreakingAnimation(RenderEnv.java:157)
	at net.optifine.model.BlockModelCustomizer.getRenderQuads(BlockModelCustomizer.java:54)
	at net.minecraft.client.renderer.BlockModelRenderer.renderModelSmooth(BlockModelRenderer.java:145)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.renderModelSmooth(ForgeBlockModelRenderer.java:89)

-- Block model being tesselated --
Details:
	Block: Block{doubleslabs:double_slab}
	Block location: World: (1160,71,965), Chunk: (at 8,4,5 in 72,60; contains blocks 1152,0,960 to 1167,255,975), Region: (2,1; contains chunks 64,32 to 95,63, blocks 1024,0,512 to 1535,255,1023)
	Using AO: true
Stacktrace:
	at net.minecraft.client.renderer.BlockModelRenderer.renderModel(BlockModelRenderer.java:101)

-- Block being tesselated --
Details:
	Block: Block{doubleslabs:double_slab}
	Block location: World: (1160,71,965), Chunk: (at 8,4,5 in 72,60; contains blocks 1152,0,960 to 1167,255,975), Region: (2,1; contains chunks 64,32 to 95,63, blocks 1024,0,512 to 1535,255,1023)
Stacktrace:
	at net.minecraft.client.renderer.BlockRendererDispatcher.renderModel(BlockRendererDispatcher.java:82)
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$ChunkRender$RebuildTask.func_228940_a_(ChunkRenderDispatcher.java:877)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['FPCAFox'/35, l='MpServer', x=1161.50, y=73.28, z=955.49]]
	Chunk stats: Client Chunk Cache: 441, 240
	Level dimension: DimensionType{minecraft:overworld}
	Level name: MpServer
	Level seed: -170274042140503633
	Level generator: ID 07 - biomesoplenty, ver 0. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (-38,63,191), Chunk: (at 10,3,15 in -3,11; contains blocks -48,0,176 to -33,255,191), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 41147 game time, 41147 day time
	Known server brands: 
	Level was modded: false
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: true), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:611)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1763)
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.lambda$runTask$3(ChunkRenderDispatcher.java:186)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(Unknown Source)
	at java.util.concurrent.CompletableFuture.whenComplete(Unknown Source)
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.func_228909_h_(ChunkRenderDispatcher.java:181)
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.lambda$schedule$4(ChunkRenderDispatcher.java:252)
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213148_e(SourceFile:83)
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213145_a(SourceFile:123)
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.run(SourceFile:91)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source)
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_211, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2090387664 bytes (1993 MB) / 5074059264 bytes (4839 MB) up to 10630070272 bytes (10137 MB)
	CPUs: 12
	JVM Flags: 26 total; -Xmn1024m -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+UseNUMA -XX:+CMSParallelRemarkEnabled -XX:MaxTenuringThreshold=15 -XX:MaxGCPauseMillis=30 -XX:GCPauseIntervalMillis=150 -XX:+UseAdaptiveGCBoundary -XX:-UseGCOverheadLimit -XX:+UseBiasedLocking -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=15 -XX:+UseFastAccessorMethods -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:+AggressiveOpts -XX:ReservedCodeCacheSize=2048m -XX:+UseCodeCacheFlushing -XX:SoftRefLRUPolicyMSPerMB=10000 -XX:ParallelGCThreads=10 -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms1024m -Xmx10240m
	ModLauncher: 5.1.2+70+master.2845bb9
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.2.36-launcher.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.36-launcher.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.3-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.2.36-launcher.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.36-launcher.jar runtimedistcleaner PLUGINSERVICE 
		/preview_OptiFine_1.15.2_HD_U_G1_pre30.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.15.2-31.2.36-launcher.jar fml TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.3.jar mixinbootstrap TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.3.jar mixin PLUGINSERVICE 
		/MixinBootstrap-1.0.3.jar mixinbootstrap PLUGINSERVICE 
	FML: 31.2
	Forge: net.minecraftforge:31.2.36
	FML Language Providers: 
		javafml@31.2
		minecraft@1
		kotlinforforge@1.4.1
	Mod List: 
		tetra-1.15.2-2.18.1.jar Tetra {tetra@1.15.2-2.18.1 DONE}
		SaveMyStronghold-1.15.2-1.0.1.jar Save My Stronghold! {savemystronghold@1.15.2-1.0.1 DONE}
		QuarkOddities-1.15.2.jar Quark Oddities {quarkoddities@1.15.2 DONE}
		foodexpansion-1.5.3.jar Food Expansion: Reimagined {foodexpansion@1.5.3 DONE}
		SimplyJetpacks2-1.15.2-2.5.2.2.jar Simply Jetpacks 2 {simplyjetpacks@1.15.2-2.5.2.2 DONE}
		Cucumber-1.15.2-3.0.9.jar Cucumber Library {cucumber@3.0.9 DONE}
		pamhc2trees-1.15.2-1.0.7.jar Pam's HarvestCraft 2 Fruit Trees {pamhc2trees@version DONE}
		jei-1.15.2-6.0.2.14.jar Just Enough Items {jei@6.0.2.14 DONE}
		futuremc-1.15.2-1.0.1.jar Future MC {futuremc@1.15.2-1.0.1 DONE}
		lithium-mc1.15.2-forge-0.4.6-rc3-mod.jar Lithium {lithium@0.4.6-rc3 DONE}
		FallingTree-1.15.2-2.2.1.jar Falling Tree {falling_tree@2.2.1 DONE}
		tesseract-1.0.11-mc1.15.jar Tesseract {tesseract@1.0.11 DONE}
		extrabows-v1.15.2+b2.jar Extra Bows {extrabows@v1.15.2 b2 DONE}
		BetterCaves-1.15.2-1.0.jar YUNG's Better Caves {bettercaves@1.15.2-1.0 DONE}
		Waystones_1.15.2-6.0.2.jar Waystones {waystones@6.0.2 DONE}
		TerraForged-1.15.2-0.1.2.jar TerraForged {terraforged@0.1.2 DONE}
		RingOfRepair-1.15.2-1.1.33.jar Ring of Repair {ring_of_repair@1.1.30 DONE}
		mgui-1.15.2-2.1.1.jar mgui {mgui@2.1.1 DONE}
		CTM-MC1.15.2-1.1.1.13.jar ConnectedTexturesMod {ctm@MC1.15.2-1.1.1.13 DONE}
		CookingForBlockheads_1.15.2-8.0.3.jar Cooking for Blockheads {cookingforblockheads@8.0.3 DONE}
		comforts-FORGE-1.15.2-2.0.0.3.jar Comforts {comforts@FORGE-1.15.2-2.0.0.3 DONE}
		TravelersBackpack-1.15.2-4.0.7.jar Traveler's Backpack {travelersbackpack@4.0.7 DONE}
		SimpleStorageNetwork-1.15.2-1.0.1.jar Simple Storage Network {storagenetwork@1.15.2-1.0.1 DONE}
		culinaryconstruct-FORGE-1.15.2-2.0.0.2.jar Culinary Construct {culinaryconstruct@FORGE-1.15.2-2.0.0.2 DONE}
		betteranimalsplus-1.15.2-8.2.1.96.jar Better Animals Plus {betteranimalsplus@8.2.1.96 DONE}
		Reliquary-1.15.2-1.3.4.995.jar Reliquary {xreliquary@1.15.2-1.3.4.995 DONE}
		endercompass-2.1.jar Ender Compass {endercompass@2.1 DONE}
		BetterThanMending-1.4.0.jar BetterThanMending {betterthanmending@1.4.0 DONE}
		forge-1.15.2-31.2.36-universal.jar Forge {forge@31.2.36 DONE}
		Atum-1.15.2-2.1.4.jar Atum 2 {atum@1.15.2-2.1.4 DONE}
		MysticalAgradditions-1.15.2-3.0.1.jar Mystical Agradditions {mysticalagradditions@3.0.1 DONE}
		MysticalAgriculture-1.15.2-3.0.10.jar Mystical Agriculture {mysticalagriculture@3.0.10 DONE}
		forge-1.15.2-31.2.36-client.jar Minecraft {minecraft@1.15.2 DONE}
		theoneprobe-1.15-2.0.7.jar The One Probe {theoneprobe@1.15-2.0.7 DONE}
		ImmersiveEngineering-1.15.2-3.2.0-114.jar Immersive Engineering {immersiveengineering@1.15.2-3.2.0-114 DONE}
		BiomesOPlenty-1.15.2-10.0.0.366-universal.jar Biomes O' Plenty {biomesoplenty@1.15.2-10.0.0.366 DONE}
		phosphor-forge-mc1.15.2-0.5.2+build.4.jar Phosphor {phosphor@0.5.2+build.4 DONE}
		baubles-1.7.1-1.15.2.jar Baubles {baubles@1.7.1 DONE}
		pamhc2crops-1.15.2-1.0.5.jar Pam's HarvestCraft 2 Crops {pamhc2crops@version DONE}
		Futurepack-1.15.2-20.1.0.jar Futurepack {futurepack@20.1.0 DONE}
		towers_of_the_wild-1.15.2-1.2.0.jar Towers Of the Wild {towers_of_the_wild@1.15.2-1.2.0 DONE}
		pamhc2foodcore-1.15.2-1.0.9.jar Pam's HarvestCraft 2 Food Core {pamhc2foodcore@version DONE}
		RingOfMiner-1.15.2-1.1.31.jar Ring of Miner {ring_of_miner@1.1.28 DONE}
		AutoRegLib-1.5-40.jar AutoRegLib {autoreglib@1.5-40 DONE}
		Quark-r2.1-245.jar Quark {quark@r2.1-245 DONE}
		StorageDrawers-1.15.2-7.0.2.jar Storage Drawers {storagedrawers@1.15.2-7.0.1 DONE}
		DoubleSlabs-1.15-2.10.0.jar Double Slabs {doubleslabs@2.10.0 DONE}
		lostcities-1.15-3.0.1-alpha.jar LostCities {lostcities@1.15-3.0.1-alpha DONE}
		libnonymous-1.15.2-1.1.1.5.jar Libnonymous {libnonymous@1.1.1.5 DONE}
		expandedstorage-2.0.0+1.15.2.jar Expanded Storage {expandedstorage@2.0.0 DONE}
		worldedit-forge-mc1.15.2-7.1.0.jar WorldEdit {worldedit@7.1.0;48cc31c DONE}
		AppleSkin-mc1.15.2-forge-1.0.14.jar AppleSkin {appleskin@1.0.14 DONE}
		engineersdecor-1.15.2-1.1.2.jar Engineer's Decor {engineersdecor@1.1.2 DONE}
		moreoverlays-1.17.5-mc1.15.2.jar More Overlays Updated {moreoverlays@1.17.5-mc1.15.2 DONE}
		forgemod_VoxelMap-1.9.28_for_1.15.2.jar VoxelMap {voxelmap@1.9.28 DONE}
		SolarGeneration-1.15.2-1.2.2.jar Solar Generation {solargeneration@1.2.2 DONE}
		FastLeafDecay-v22.jar FastLeafDecay {fastleafdecay@v22 DONE}
		BetterMineshaftsForge-1.15.2-1.3.1.jar YUNG's Better Mineshafts {bettermineshafts@1.15.2-1.3.1 DONE}
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: ~~ERROR~~ IllegalStateException: Rendersystem called from wrong thread
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, mod_resources
	Current Language: English (US)
	CPU: 12x AMD Ryzen 5 1600X Six-Core Processor 
	OptiFine Version: OptiFine_1.15.2_HD_U_G1_pre30
	OptiFine Build: 20200622-083032
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.13587 Compatibility Profile Context 20.4.1 26.20.15029.20013
	OpenGlRenderer: Radeon RX 580 Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 12
 [m [32m[13:37:20] [Render thread/INFO] [STDOUT/]: [net.minecraft.util.registry.Bootstrap:func_179870_a:103]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\Mark McCloud\AppData\Roaming\.minecraft\MultiMC\instances\Vanilla 1.15.2\.minecraft\crash-reports\crash-2020-08-26_13.37.20-client.txt
 [mSaving all world maps [32m[13:37:20] [Server thread/INFO] [st.si.SimplyJetpacks/]: Server stopping...
 [m [32m[13:37:20] [Server thread/INFO] [co.sk.wo.ex.pl.PlatformManager/]: Unregistering com.sk89q.worldedit.forge.ForgePlatform from WorldEdit
 [m.
AL lib: (EE) alc_cleanup: 1 device not closed.

**Comment by FSwordFoxA** [comment]
Disabling tessellation for javaw (aka "the game") through the Radeon Software panel does not resolve the issue.

Using Optiforge to increase Optifine's compatibility with Forge 31.2.36 doesn't resolve the crash. All it did was allow me to place down a few more slabs before it crashed.

Disabling Optifine or DoubleSlabs obviously resolves the crash.

**Comment by FSwordFoxA** [comment]
Further investigation suggests that this may have been triggered by Optifine 1.15.2_HD_U_G1_pre30 not having support for Forge versions newer than 31.2.21.

So it is either disable Optifine, disable Double Slabs, or run an older version of Forge _**and**_ disable any mods that aren't compatible with said older forge version.

This feels like an Optifine issue now, as they are still focused on 1.16 at this time. They may come back to 1.15 and produce full release versions for Forge versions more recent than 31.2.21.

**Comment by CJMinecraft01** [comment]
Can you try this in the latest version please?

**Comment by FSwordFoxA** [comment]
> 
> 
> Can you try this in the latest version please?

So far so good. I'll continue tests on and off to see if it is truly resolved.
