### ISSUE TITLE
crash while placing a slab on top of another slab

### ISSUE THREAD

**Issue by texaswriter** [CJMinecraft01/DoubleSlabs#16]
What I was doing: 
 I was placing a slab on top of another slab on a SMP server when the client crashed. Relogging was fine. 

Attached is a crash report. 

[crash-2020-03-19_23.32.41-client.txt](https://github.com/CJMinecraft01/DoubleSlabs/files/4357961/crash-2020-03-19_23.32.41-client.txt)

Useful snippet from crash report: 

---- Minecraft Crash Report ----
// Would you like a cupcake?

Time: 3/19/20 11:32 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at cjminecraft.doubleslabs.blocks.BlockDoubleSlab.lambda$getPickBlock$6(BlockDoubleSlab.java:130) ~[?:2.0.1] {re:classloading}
	at cjminecraft.doubleslabs.blocks.BlockDoubleSlab.runOnDoubleSlab(BlockDoubleSlab.java:88) ~[?:2.0.1] {re:classloading}
	at cjminecraft.doubleslabs.blocks.BlockDoubleSlab.getPickBlock(BlockDoubleSlab.java:130) ~[?:2.0.1] {re:classloading}
	at mcp.mobius.waila.api.impl.DataAccessor.set(DataAccessor.java:54) ~[?:1.10.8-B72_1.15.2] {re:classloading}
	at mcp.mobius.waila.api.impl.DataAccessor.set(DataAccessor.java:39) ~[?:1.10.8-B72_1.15.2] {re:classloading}
	at mcp.mobius.waila.overlay.WailaTickHandler.tickClient(WailaTickHandler.java:58) ~[?:1.10.8-B72_1.15.2] {re:classloading}
	at mcp.mobius.waila.WailaClient.onClientTick(WailaClient.java:112) ~[?:1.10.8-B72_1.15.2] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_97_WailaClient_onClientTick_ClientTickEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPostClientTick(BasicEventHooks.java:109) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1450) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:905) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:554) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:204) ~[1.15.2-forge-31.1.24.jar:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) ~[forge-1.15.2-31.1.24.jar:31.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.0.0-milestone.4.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.0.0-milestone.4.jar:?] {re:classloading}

**Comment by CJMinecraft01** [comment]
Hi, thanks for the bug report. Have you tried updating DoubleSlabs to the latest version?

**Comment by BigPingo2** [comment]
Same happened with me, I was placing a floor down and I accidentally placed another slab underneath the same type and game crashed, logged back in and whenever I tried breaking it it kept crashing. Removed the mod and works fine now.

**Comment by BigPingo2** [comment]
Oh yeah, I just tried it out and placing 2 different slabs on top of eachother worked fine, but it was when I break any 2 slabs that are on eachother, different or not, the game crashes. Here's what it says:
java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=variant, clazz=class net.minecraft.block.BlockPlanks$EnumType, values=[oak, spruce, birch, jungle, acacia, dark_oak]} as it does not exist in ExtendedBlockState{block=doubleslabs:double_slab, properties=[]}
I also am running the latest version for 1.12(.2) of this mod. Hope this helps!

**Comment by CJMinecraft01** [comment]
The second issue you mentioned @BigPingo2 is a duplicate of #14. Was the first issue fixed with the newer version?

**Comment by BigPingo2** [comment]
It was not fixed in the newest version @CJMinecraft01

**Comment by CJMinecraft01** [comment]
I can't seem to recreate your first issue. Could you please try and update to the latest version and tell me which slabs you tried to place together?

**Comment by CJMinecraft01** [comment]
Closing due to inactivity
