### ISSUE TITLE
Client cannot connect to server with 0.11.1

### ISSUE THREAD

**Issue by Sixdd6** [CJMinecraft01/DoubleSlabs#170]
Continuation from #154, new version posted there, poster does not allow issues on their fork so I'm hoping they see this here.

When trying to connect to a server with 0.11.1 I get the following in server log and cannot connect to server:

```
[Server thread/WARN] [minecraft/NetworkSystem]: Failed to handle packet for "IP Address Removed for Privacy"
java.lang.NullPointerException: null
	at cjminecraft.doubleslabs.api.ServerWorldWrapper.func_72860_G(ServerWorldWrapper.java:1163) ~[ServerWorldWrapper.class:0.11.1]
	at com.pg85.otg.forge.world.OTGWorldType.getBiomeProvider(OTGWorldType.java:143) ~[OTGWorldType.class:?]
	at net.minecraft.world.WorldProvider.func_76572_b(WorldProvider.java:58) ~[aym.class:?]
	at net.minecraft.world.WorldProvider.func_76558_a(WorldProvider.java:40) ~[aym.class:?]
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:116) ~[oo.class:?]
	at cjminecraft.doubleslabs.api.ServerWorldWrapper.<init>(ServerWorldWrapper.java:85) ~[ServerWorldWrapper.class:0.11.1]
	at cjminecraft.doubleslabs.api.BlockInfo.setWorld(BlockInfo.java:115) ~[BlockInfo.class:0.11.1]
	at cjminecraft.doubleslabs.common.tileentity.SlabTileEntity.func_145834_a(SlabTileEntity.java:89) ~[SlabTileEntity.class:0.11.1]
	at net.minecraft.world.chunk.Chunk.func_177426_a(Chunk.java:825) ~[axw.class:?]
	at net.minecraft.world.chunk.Chunk.func_150813_a(Chunk.java:814) ~[axw.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:499) ~[aye.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:101) ~[ChunkIOProvider.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94) ~[ChunkIOExecutor.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:118) ~[on.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:89) ~[on.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:135) ~[on.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:310) ~[amu.class:?]
	at net.minecraft.world.World.func_72838_d(World.java:1211) ~[amu.class:?]
	at net.minecraft.world.WorldServer.func_72838_d(WorldServer.java:1058) ~[oo.class:?]
	at net.minecraft.server.management.PlayerList.func_72377_c(PlayerList.java:377) ~[pl.class:?]
	at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:166) ~[pl.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:255) ~[NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:72) ~[NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:205) ~[NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) ~[gw.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]
```
Full log is attatched: [latest.log](https://github.com/CJMinecraft01/DoubleSlabs/files/5753943/latest.log)

**Comment by TheidenHD** [comment]
This is an incompatibility betwent DoubleSlabs and OpenTerrainGenerator.

**Comment by Sixdd6** [comment]
Yes, I figured as much from reading the log. I'm hoping it's something that can be fixed since previous versions of DoubleSlabs have no issue with OTG.

**Comment by CJMinecraft01** [comment]
Hi there! Sorry for the delay, this is now fixed in the latest version :)
