### ISSUE TITLE
Crash when interacting with glitched slab block

### ISSUE THREAD

**Issue by pseudoble** [CJMinecraft01/DoubleSlabs#223]
I have a build with a lot of vertical slabs. Recently, even updated to 3.7.2 on 1.16.5, I have had problems where a ton of them load in without any texture (transparent). If I try to break of of these blocks, even in creative, it crashes my client with the following error. No evidence of anything wrong on the server logs. 

28/09/2021 22:36:55 PM] [22:36:55] [Render thread/FATAL] [minecraft/Minecraft]: Reported exception thrown!
[28/09/2021 22:36:55 PM] net.minecraft.crash.ReportedException: Playing level event
[28/09/2021 22:36:55 PM] 	at net.minecraft.client.world.ClientWorld.func_217378_a(ClientWorld.java:580) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:APP:create.mixins.json:BreakProgressMixin,pl:mixin:A,pl:runtimedistcleaner:A}
[28/09/2021 22:36:55 PM] 	at net.minecraft.block.Block.func_176208_a(Block.java:361) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:framedblocks.mixin.json:MixinBlock,pl:mixin:A}
[28/09/2021 22:36:55 PM] 	at cjminecraft.doubleslabs.common.blocks.DynamicSlabBlock.func_176208_a(DynamicSlabBlock.java:240) ~[doubleslabs:3.7.2] {re:mixin,re:classloading}
[28/09/2021 22:36:55 PM] 	at net.minecraftforge.common.extensions.IForgeBlock.removedByPlayer(IForgeBlock.java:213) ~[forge:?] {re:mixin,re:classloading}
[28/09/2021 22:36:55 PM] 	at cjminecraft.doubleslabs.common.blocks.DynamicSlabBlock.removedByPlayer(DynamicSlabBlock.java:233) ~[doubleslabs:3.7.2] {re:mixin,re:classloading}
[28/09/2021 22:36:55 PM] 	at cjminecraft.doubleslabs.common.blocks.VerticalSlabBlock.removedByPlayer(VerticalSlabBlock.java:227) ~[doubleslabs:3.7.2] {re:classloading,re:mixin}
[28/09/2021 22:36:55 PM] 	at net.minecraftforge.common.extensions.IForgeBlockState.removedByPlayer(IForgeBlockState.java:157) ~[forge:?] {re:mixin,re:classloading}
[28/09/2021 22:36:55 PM] 	at net.minecraft.client.multiplayer.PlayerController.func_187103_a(PlayerController.java:112) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
[28/09/2021 22:36:55 PM] 	at net.minecraft.client.multiplayer.PlayerController.func_180511_b(PlayerController.java:134) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
[28/09/2021 22:36:55 PM] 	at net.minecraft.client.Minecraft.func_147116_af(Minecraft.java:1311) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
[28/09/2021 22:36:55 PM] 	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:1641) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
[28/09/2021 22:36:55 PM] 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1460) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
[28/09/2021 22:36:55 PM] 	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
[28/09/2021 22:36:55 PM] 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
[28/09/2021 22:36:55 PM] 	at net.minecraft.client.main.Main.main(Main.java:184) ~[client-1.16.5.jar:?] {re:classloading,pl:runtimedistcleaner:A}
[28/09/2021 22:36:55 PM] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_202] {}
[28/09/2021 22:36:55 PM] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_202] {}
[28/09/2021 22:36:55 PM] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_202] {}
[28/09/2021 22:36:55 PM] 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_202] {re:computing_frames}
[28/09/2021 22:36:55 PM] 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.2.6.jar:36.2] {}
[28/09/2021 22:36:55 PM] 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
[28/09/2021 22:36:55 PM] 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
[28/09/2021 22:36:55 PM] 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
[28/09/2021 22:36:55 PM] 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
[28/09/2021 22:36:55 PM] 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}
[28/09/2021 22:36:55 PM] Caused by: java.lang.NullPointerException
[28/09/2021 22:36:55 PM] 	at cjminecraft.doubleslabs.common.blocks.VerticalSlabBlock.lambda$getSoundType$23(VerticalSlabBlock.java:490) ~[doubleslabs:3.7.2] {re:classloading,re:mixin}
[28/09/2021 22:36:55 PM] 	at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_202] {}
[28/09/2021 22:36:55 PM] 	at cjminecraft.doubleslabs.common.blocks.VerticalSlabBlock.getSoundType(VerticalSlabBlock.java:490) ~[doubleslabs:3.7.2] {re:classloading,re:mixin}
[28/09/2021 22:36:55 PM] 	at net.minecraftforge.common.extensions.IForgeBlockState.getSoundType(IForgeBlockState.java:567) ~[forge:?] {re:mixin,re:classloading}
[28/09/2021 22:36:55 PM] 	at net.minecraft.client.renderer.WorldRenderer.func_180439_a(WorldRenderer.java:2418) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
[28/09/2021 22:36:55 PM] 	at net.minecraft.client.world.ClientWorld.func_217378_a(ClientWorld.java:572) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:APP:create.mixins.json:BreakProgressMixin,pl:mixin:A,pl:runtimedistcleaner:A}
[28/09/2021 22:36:55 PM] 	... 24 more
[28/09/2021 22:36:55 PM] [22:36:55] [Render thread/INFO] [STDOUT/]: [net.minecraft.util.registry.Bootstrap:func_179870_a:123]: ---- Minecraft Crash Report ----
[28/09/2021 22:36:55 PM] // There are four lights!
[28/09/2021 22:36:55 PM] 
[28/09/2021 22:36:55 PM] Time: 9/28/21 10:36 PM
[28/09/2021 22:36:55 PM] Description: Playing level event
[28/09/2021 22:36:55 PM] 
[28/09/2021 22:36:55 PM] java.lang.NullPointerException: Playing level event
[28/09/2021 22:36:55 PM] 	at cjminecraft.doubleslabs.common.blocks.VerticalSlabBlock.lambda$getSoundType$23(VerticalSlabBlock.java:490) ~[doubleslabs:3.7.2] {re:classloading,re:mixin}
[28/09/2021 22:36:55 PM] 	at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_202] {}
[28/09/2021 22:36:55 PM] 	at cjminecraft.doubleslabs.common.blocks.VerticalSlabBlock.getSoundType(VerticalSlabBlock.java:490) ~[doubleslabs:3.7.2] {re:classloading,re:mixin}
[28/09/2021 22:36:55 PM] 	at net.minecraftforge.common.extensions.IForgeBlockState.getSoundType(IForgeBlockState.java:567) ~[forge:?] {re:mixin,re:classloading}
[28/09/2021 22:36:55 PM] 	at net.minecraft.client.renderer.WorldRenderer.func_180439_a(WorldRenderer.java:2418) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
[28/09/2021 22:36:55 PM] 	at net.minecraft.client.world.ClientWorld.func_217378_a(ClientWorld.java:572) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:APP:create.mixins.json:BreakProgressMixin,pl:mixin:A,pl:runtimedistcleaner:A}
[28/09/2021 22:36:55 PM] 	at net.minecraft.block.Block.func_176208_a(Block.java:361) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:framedblocks.mixin.json:MixinBlock,pl:mixin:A}
[28/09/2021 22:36:55 PM] 	at cjminecraft.doubleslabs.common.blocks.DynamicSlabBlock.func_176208_a(DynamicSlabBlock.java:240) ~[doubleslabs:3.7.2] {re:mixin,re:classloading}
[28/09/2021 22:36:55 PM] 	at net.minecraftforge.common.extensions.IForgeBlock.removedByPlayer(IForgeBlock.java:213) ~[forge:?] {re:mixin,re:classloading}
[28/09/2021 22:36:55 PM] 	at cjminecraft.doubleslabs.common.blocks.DynamicSlabBlock.removedByPlayer(DynamicSlabBlock.java:233) ~[doubleslabs:3.7.2] {re:mixin,re:classloading}
[28/09/2021 22:36:55 PM] 	at cjminecraft.doubleslabs.common.blocks.VerticalSlabBlock.removedByPlayer(VerticalSlabBlock.java:227) ~[doubleslabs:3.7.2] {re:classloading,re:mixin}
[28/09/2021 22:36:55 PM] 	at net.minecraftforge.common.extensions.IForgeBlockState.removedByPlayer(IForgeBlockState.java:157) ~[forge:?] {re:mixin,re:classloading}
[28/09/2021 22:36:55 PM] 	at net.minecraft.client.multiplayer.PlayerController.func_187103_a(PlayerController.java:112) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
[28/09/2021 22:36:55 PM] 	at net.minecraft.client.multiplayer.PlayerController.func_180511_b(PlayerController.java:134) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
[28/09/2021 22:36:55 PM] 	at net.minecraft.client.Minecraft.func_147116_af(Minecraft.java:1311) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
[28/09/2021 22:36:55 PM] 	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:1641) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
[28/09/2021 22:36:55 PM] 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1460) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
[28/09/2021 22:36:55 PM] 	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
[28/09/2021 22:36:55 PM] 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
[28/09/2021 22:36:55 PM] 	at net.minecraft.client.main.Main.main(Main.java:184) ~[client-1.16.5.jar:?] {re:classloading,pl:runtimedistcleaner:A}
[28/09/2021 22:36:55 PM] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_202] {}
[28/09/2021 22:36:55 PM] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_202] {}
[28/09/2021 22:36:55 PM] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_202] {}
[28/09/2021 22:36:55 PM] 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_202] {re:computing_frames}
[28/09/2021 22:36:55 PM] 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.2.6.jar:36.2] {}
[28/09/2021 22:36:55 PM] 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
[28/09/2021 22:36:55 PM] 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
[28/09/2021 22:36:55 PM] 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
[28/09/2021 22:36:55 PM] 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
[28/09/2021 22:36:55 PM] 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}
[28/09/2021 22:36:55 PM] 
[28/09/2021 22:36:55 PM] 
[28/09/2021 22:36:55 PM] A detailed walkthrough of the error, its code path and all known details is as follows:
[28/09/2021 22:36:55 PM] ---------------------------------------------------------------------------------------
[28/09/2021 22:36:55 PM] 
[28/09/2021 22:36:55 PM] -- Head --
[28/09/2021 22:36:55 PM] Thread: Render thread
[28/09/2021 22:36:55 PM] Stacktrace:
[28/09/2021 22:36:55 PM] 	at cjminecraft.doubleslabs.common.blocks.VerticalSlabBlock.lambda$getSoundType$23(VerticalSlabBlock.java:490) ~[doubleslabs:3.7.2] {re:classloading,re:mixin}
[28/09/2021 22:36:55 PM] 	at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_202] {}
[28/09/2021 22:36:55 PM] 	at cjminecraft.doubleslabs.common.blocks.VerticalSlabBlock.getSoundType(VerticalSlabBlock.java:490) ~[doubleslabs:3.7.2] {re:classloading,re:mixin}
[28/09/2021 22:36:55 PM] 	at net.minecraftforge.common.extensions.IForgeBlockState.getSoundType(IForgeBlockState.java:567) ~[forge:?] {re:mixin,re:classloading}
[28/09/2021 22:36:55 PM] 	at net.minecraft.client.renderer.WorldRenderer.func_180439_a(WorldRenderer.java:2418) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
[28/09/2021 22:36:55 PM] -- Level event being played --
[28/09/2021 22:36:55 PM] Details:
[28/09/2021 22:36:55 PM] 	Block coordinates: World: (266,21,66), Chunk: (at 10,1,2 in 16,4; contains blocks 256,0,64 to 271,255,79), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
[28/09/2021 22:36:55 PM] 	Event source: ClientPlayerEntity['**MINECRAFTUSERNAME**'/17848, l='ClientLevel', x=267.07, y=20.21, z=69.43]
[28/09/2021 22:36:55 PM] 	Event type: 2001
[28/09/2021 22:36:55 PM] 	Event data: 157515
[28/09/2021 22:36:55 PM] Stacktrace:
[28/09/2021 22:36:55 PM] 	at net.minecraft.client.world.ClientWorld.func_217378_a(ClientWorld.java:572) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:APP:create.mixins.json:BreakProgressMixin,pl:mixin:A,pl:runtimedistcleaner:A}
[28/09/2021 22:36:55 PM] 	at net.minecraft.block.Block.func_176208_a(Block.java:361) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:framedblocks.mixin.json:MixinBlock,pl:mixin:A}
[28/09/2021 22:36:55 PM] 	at cjminecraft.doubleslabs.common.blocks.DynamicSlabBlock.func_176208_a(DynamicSlabBlock.java:240) ~[doubleslabs:3.7.2] {re:mixin,re:classloading}
[28/09/2021 22:36:55 PM] 	at net.minecraftforge.common.extensions.IForgeBlock.removedByPlayer(IForgeBlock.java:213) ~[forge:?] {re:mixin,re:classloading}
[28/09/2021 22:36:55 PM] 	at cjminecraft.doubleslabs.common.blocks.DynamicSlabBlock.removedByPlayer(DynamicSlabBlock.java:233) ~[doubleslabs:3.7.2] {re:mixin,re:classloading}
[28/09/2021 22:36:55 PM] 	at cjminecraft.doubleslabs.common.blocks.VerticalSlabBlock.removedByPlayer(VerticalSlabBlock.java:227) ~[doubleslabs:3.7.2] {re:classloading,re:mixin}
[28/09/2021 22:36:55 PM] 	at net.minecraftforge.common.extensions.IForgeBlockState.removedByPlayer(IForgeBlockState.java:157) ~[forge:?] {re:mixin,re:classloading}
[28/09/2021 22:36:55 PM] 	at net.minecraft.client.multiplayer.PlayerController.func_187103_a(PlayerController.java:112) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
[28/09/2021 22:36:55 PM] 	at net.minecraft.client.multiplayer.PlayerController.func_180511_b(PlayerController.java:134) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
[28/09/2021 22:36:55 PM] 	at net.minecraft.client.Minecraft.func_147116_af(Minecraft.java:1311) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
[28/09/2021 22:36:55 PM] 	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:1641) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
[28/09/2021 22:36:55 PM] 
[28/09/2021 22:36:55 PM] 
[28/09/2021 22:36:55 PM] -- Affected level --
[28/09/2021 22:36:55 PM] Details:
[28/09/2021 22:36:55 PM] 	All players: 1 total; [ClientPlayerEntity['**MINECRAFTUSERNAME**'/17848, l='ClientLevel', x=267.07, y=20.21, z=69.43]]
[28/09/2021 22:36:55 PM] 	Chunk stats: Client Chunk Cache: 729, 484
[28/09/2021 22:36:55 PM] 	Level dimension: minecraft:overworld
[28/09/2021 22:36:55 PM] 	Level spawn location: World: (-119,63,-287), Chunk: (at 9,3,1 in -8,-18; contains blocks -128,0,-288 to -113,255,-273), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
[28/09/2021 22:36:55 PM] 	Level time: 165232718 game time, 180859593 day time
[28/09/2021 22:36:55 PM] 	Server brand: forge
[28/09/2021 22:36:55 PM] 	Server type: Non-integrated multiplayer server
[28/09/2021 22:36:55 PM] Stacktrace:
[28/09/2021 22:36:55 PM] 	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:447) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:APP:create.mixins.json:BreakProgressMixin,pl:mixin:A,pl:runtimedistcleaner:A}
[28/09/2021 22:36:55 PM] 	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2029) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
[28/09/2021 22:36:55 PM] 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:623) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
[28/09/2021 22:36:55 PM] 	at net.minecraft.client.main.Main.main(Main.java:184) ~[client-1.16.5.jar:?] {re:classloading,pl:runtimedistcleaner:A}
[28/09/2021 22:36:55 PM] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_202] {}
[28/09/2021 22:36:55 PM] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_202] {}
[28/09/2021 22:36:55 PM] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_202] {}
[28/09/2021 22:36:55 PM] 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_202] {re:computing_frames}
[28/09/2021 22:36:55 PM] 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.2.6.jar:36.2] {}
[28/09/2021 22:36:55 PM] 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
[28/09/2021 22:36:55 PM] 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
[28/09/2021 22:36:55 PM] 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
[28/09/2021 22:36:55 PM] 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
[28/09/2021 22:36:55 PM] 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}
[28/09/2021 22:36:55 PM] 
[28/09/2021 22:36:55 PM] 
[28/09/2021 22:36:55 PM] -- System Details --
[28/09/2021 22:36:55 PM] Details:
[28/09/2021 22:36:55 PM] 	Minecraft Version: 1.16.5
[28/09/2021 22:36:55 PM] 	Minecraft Version ID: 1.16.5
[28/09/2021 22:36:55 PM] 	Operating System: Linux (amd64) version 5.11.22-2-MANJARO
[28/09/2021 22:36:55 PM] 	Java Version: 1.8.0_202, Oracle Corporation
[28/09/2021 22:36:55 PM] 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
[28/09/2021 22:36:55 PM] 	Memory: 5855933136 bytes (5584 MB) / 9965666304 bytes (9504 MB) up to 12683575296 bytes (12096 MB)
[28/09/2021 22:36:55 PM] 	CPUs: 24
[28/09/2021 22:36:55 PM] 	JVM Flags: 12 total; -XX:-OmitStackTraceInFastThrow -Xms512M -Xmx12096M -XX:MetaspaceSize=256M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -Xss1M -XX:+IgnoreUnrecognizedVMOptions
[28/09/2021 22:36:55 PM] 	ModLauncher: 8.0.9+86+master.3cf110c
[28/09/2021 22:36:55 PM] 	ModLauncher launch target: fmlclient
[28/09/2021 22:36:55 PM] 	ModLauncher naming: srg
[28/09/2021 22:36:55 PM] 	ModLauncher services: 
[28/09/2021 22:36:55 PM] 		/mixin-0.8.4.jar mixin PLUGINSERVICE 
[28/09/2021 22:36:55 PM] 		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
[28/09/2021 22:36:55 PM] 		/forge-1.16.5-36.2.6.jar object_holder_definalize PLUGINSERVICE 
[28/09/2021 22:36:55 PM] 		/forge-1.16.5-36.2.6.jar runtime_enum_extender PLUGINSERVICE 
[28/09/2021 22:36:55 PM] 		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
[28/09/2021 22:36:55 PM] 		/forge-1.16.5-36.2.6.jar capability_inject_definalize PLUGINSERVICE 
[28/09/2021 22:36:55 PM] 		/forge-1.16.5-36.2.6.jar runtimedistcleaner PLUGINSERVICE 
[28/09/2021 22:36:55 PM] 		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
[28/09/2021 22:36:55 PM] 		/forge-1.16.5-36.2.6.jar fml TRANSFORMATIONSERVICE 
[28/09/2021 22:36:55 PM] 		/_MixinBootstrap-1.1.0.jar mixinbootstrap TRANSFORMATIONSERVICE 
[28/09/2021 22:36:55 PM] 	FML: 36.2
[28/09/2021 22:36:55 PM] 	Forge: net.minecraftforge:36.2.6
[28/09/2021 22:36:55 PM] 	FML Language Providers: 
[28/09/2021 22:36:55 PM] 		javafml@36.2
[28/09/2021 22:36:55 PM] 		minecraft@1
[28/09/2021 22:36:55 PM] 		scorge@3.1.3
[28/09/2021 22:36:55 PM] 	Mod List: 
[28/09/2021 22:36:55 PM] 		torchslabmod-1.16.4_v1.6.19.jar                   |Torch Slab Mod                |torchslabmod                  |1.6.18              |DONE      |Manifest: NOSIGNATURE
[28/09/2021 22:36:55 PM] 		advancedperipherals-1.16.5-0.7.2r.jar             |Advanced Peripherals          |advancedperipherals           |0.7.2r              |DONE      |Manifest: NOSIGNATURE
[28/09/2021 22:36:55 PM] [22:36:55] [Render thread/INFO] [STDOUT/]: [net.minecraft.util.registry.Bootstrap:func_179870_a:123]: #@!@# Game crashed! Crash report saved to: #@!@# **USERSDIR**/instances/DDHServer/crash-reports/crash-2021-09-28_22.36.55-client.txt
[28/09/2021 22:36:55 PM] AL lib: (EE) alc_cleanup: 1 device not closed
[28/09/2021 22:36:55 PM] Oh no. Minecraft crashed. Please check the logs for any errors and provide these logs when asking for support.

**Comment by CJMinecraft01** [comment]
Hi there! Apologies for the slow response, I've had an extremely hectic year at university and have only just got round to looking at the issues. I think I have just fixed it and so this will hopefully be fixed in the next version
