### ISSUE TITLE
Error as soon as run

### ISSUE THREAD

**Issue by BeeBlob-Enby** [CJMinecraft01/DoubleSlabs#243]
---- Minecraft Crash Report -------- Minecraft Crash Report ----// There are four lights!
Time: 2022-07-27, 7:12 p.m.Description: Mod loading error has occurred
java.lang.Exception: Mod Loading has failed at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55) ~[forge-1.19-41.0.63-universal.jar%23159!/:?] {re:classloading} at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:170) ~[forge-1.19-41.0.63-universal.jar%23159!/:?] {re:classloading,pl:runtimedistcleaner:A} at net.minecraft.client.Minecraft.lambda$new$1(Minecraft.java:552) ~[client-1.19-20220607.102129-srg.jar%23154!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A} at net.minecraft.Util.m_137521_(Util.java:432) ~[client-1.19-20220607.102129-srg.jar%23154!/:?] {re:classloading} at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:546) ~[client-1.19-20220607.102129-srg.jar%23154!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A} at net.minecraft.client.gui.screens.LoadingOverlay.m_6305_(LoadingOverlay.java:135) ~[client-1.19-20220607.102129-srg.jar%23154!/:?] {re:classloading,pl:runtimedistcleaner:A} at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:885) ~[client-1.19-20220607.102129-srg.jar%23154!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A} at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1070) ~[client-1.19-20220607.102129-srg.jar%23154!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A} at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:660) ~[client-1.19-20220607.102129-srg.jar%23154!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A} at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.19-20220607.102129-srg.jar%23154!/:?] {re:classloading,pl:runtimedistcleaner:A} at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {} at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {} at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {} at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {} at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19-41.0.63.jar%2393!/:?] {} at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.1.jar%2381!/:?] {} at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.1.jar%2381!/:?] {} at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.1.jar%2381!/:?] {} at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.1.jar%2381!/:?] {} at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.1.jar%2381!/:?] {} at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.1.jar%2381!/:?] {} at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.1.jar%2381!/:?] {} at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.1.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:---------------------------------------------------------------------------------------
-- Head --Thread: Render threadStacktrace: at cjminecraft.doubleslabs.common.init.DSTiles.<clinit>(DSTiles.java:13) ~[DoubleSlabs-1.19-6.1.0.jar%23147!/:6.1.0] {re:classloading}-- MOD doubleslabs --Details: Caused by 0: java.lang.reflect.InvocationTargetException at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {} at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {} at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {} at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {} at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {} at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19-41.0.63.jar%23156!/:?] {} at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19-41.0.63.jar%23155!/:?] {} at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {} at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {} at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {} at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {} at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {} at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {} at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}
Mod File: DoubleSlabs-1.19-6.1.0.jar Failure message: Double Slabs (doubleslabs) has failed to load correctly java.lang.reflect.InvocationTargetException: null Mod Version: 6.1.0 Mod Issue URL: https://github.com/CJMinecraft01/DoubleSlabs/issues Exception message: java.lang.NoSuchFieldError: BLOCK_ENTITY_TYPESStacktrace: at cjminecraft.doubleslabs.common.init.DSTiles.<clinit>(DSTiles.java:13) ~[DoubleSlabs-1.19-6.1.0.jar%23147!/:6.1.0] {re:classloading} at cjminecraft.doubleslabs.common.DoubleSlabs.<init>(DoubleSlabs.java:60) ~[DoubleSlabs-1.19-6.1.0.jar%23147!/:6.1.0] {re:classloading} at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {} at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {} at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {} at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {} at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {} at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19-41.0.63.jar%23156!/:?] {} at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19-41.0.63.jar%23155!/:?] {} at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {} at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {} at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {} at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {} at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {} at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {} at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

-- System Details --Details: Minecraft Version: 1.19 Minecraft Version ID: 1.19 Operating System: Windows 10 (amd64) version 10.0 Java Version: 17.0.3, Microsoft Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft Memory: 1647009064 bytes (1570 MiB) / 2315255808 bytes (2208 MiB) up to 3154116608 bytes (3008 MiB) CPUs: 4 Processor Vendor: GenuineIntel Processor Name: Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz Identifier: Intel64 Family 6 Model 61 Stepping 4 Microarchitecture: Broadwell (Client) Frequency (GHz): 2.00 Number of physical packages: 1 Number of physical CPUs: 2 Number of logical CPUs: 4 Graphics card #0 name: Intel(R) HD Graphics 5500 Graphics card #0 vendor: Intel Corporation (0x8086) Graphics card #0 VRAM (MB): 1024.00 Graphics card #0 deviceId: 0x1616 Graphics card #0 versionInfo: DriverVersion=20.19.15.5058 Memory slot #0 capacity (MB): 4096.00 Memory slot #0 clockSpeed (GHz): 1.60 Memory slot #0 type: DDR3 Virtual memory max (MB): 13227.02 Virtual memory used (MB): 7121.76 Swap memory total (MB): 9216.00 Swap memory used (MB): 1082.39 JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2987M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M ModLauncher: 10.0.1+10.0.1+main.e9521dc3 ModLauncher launch target: forgeclient ModLauncher naming: srg ModLauncher services:  mixin PLUGINSERVICE  eventbus PLUGINSERVICE  slf4jfixer PLUGINSERVICE  object_holder_definalize PLUGINSERVICE  runtime_enum_extender PLUGINSERVICE  capability_token_subclass PLUGINSERVICE  accesstransformer PLUGINSERVICE  runtimedistcleaner PLUGINSERVICE  mixin TRANSFORMATIONSERVICE  OptiFine TRANSFORMATIONSERVICE  fml TRANSFORMATIONSERVICE  FML Language Providers:  minecraft@1.0 lowcodefml@null javafml@null Mod List:  client-1.19-20220607.102129-srg.jar               |Minecraft                     |minecraft                     |1.19                |COMMON_SET|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f DoubleSlabs-1.19-6.1.0.jar                        |Double Slabs                  |doubleslabs                   |6.1.0               |ERROR     |Manifest: NOSIGNATURE carryon-1.19-1.18.0.1.jar                         |Carry On                      |carryon                       |1.18.0.1            |COMMON_SET|Manifest: NOSIGNATURE CaptureAmob-Forge-1.19-1.0.1.jar                  |Capture a mob                 |capturetomob                  |1.0.1               |COMMON_SET|Manifest: NOSIGNATURE QuarkOddities-1.18.jar                            |Quark Oddities                |quarkoddities                 |1.18                |COMMON_SET|Manifest: NOSIGNATURE Healing+Bed+1.19.jar                              |Healingbed                    |healingbed                    |1.19                |COMMON_SET|Manifest: NOSIGNATURE LibraryFerret-Forge-1.19-1.0.3.jar                |Library ferret                |libraryferret                 |1.0.3               |COMMON_SET|Manifest: NOSIGNATURE forge-1.19-41.0.63-universal.jar                  |Forge                         |forge                         |41.0.63             |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90 tl_skin_cape_forge_1.19-1.26.jar                  |TLSkinCape                    |tlskincape                    |1.26                |COMMON_SET|Manifest: 19:f5:ce:44:81:0c:e4:22:05:5e:73:c5:a8:cd:de:f3:c8:cf:a9:b3:01:70:40:a0:ee:2d:50:7a:1c:3d:1c:8a unlitcampfire-forge-1.19-1.6.0.0.jar              |Unlit Campfire                |unlitcampfire                 |1.19-1.6.0.0        |COMMON_SET|Manifest: NOSIGNATURE forgivingvoid-forge-1.19-7.0.0.jar                |Forgiving Void                |forgivingvoid                 |7.0.0               |COMMON_SET|Manifest: NOSIGNATURE balm-4.0.0+0.jar                                  |Balm                          |balm                          |4.0.0+0             |COMMON_SET|Manifest: NOSIGNATURE Crash Report UUID: 3e1247b8-3d53-469d-8d80-3183b56b20ec FML: 41.0 Forge: net.minecraftforge:41.0.63

**Comment by CJMinecraft01** [comment]
Hi there! Thanks for the report. It seems like the issue is due to a breaking change in forge at version 41.0.94. Please would you mind using a later version of forge and checking if this is fixed?
