### ISSUE TITLE
[BUG]Crash 1.12.2

### ISSUE THREAD

**Issue by UrbanSide** [CJMinecraft01/DoubleSlabs#277]
```
---- Minecraft Crash Report ----
// Lolis deobfuscated this stacktrace using MCP's stable-39 mappings.
// Surprise! Haha. Well, this is awkward.

Time: 2023-08-19 23:02:57 MSK
Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.minecraft.item.Item.func_190903_i()Lnet/minecraft/item/ItemStack;
    at cjminecraft.doubleslabs.common.items.VerticalSlabItem.lambda$getSubItems$1(VerticalSlabItem.java:59)
    at java.lang.Iterable.forEach(Unknown Source)
    at cjminecraft.doubleslabs.common.items.VerticalSlabItem.getSubItems(VerticalSlabItem.java:53)
    at crafttweaker.mc1120.item.MCItemUtils.createItemList(MCItemUtils.java:53)
    at crafttweaker.mc1120.brackets.BracketHandlerItem.rebuildItemRegistry(BracketHandlerItem.java:63)
    at crafttweaker.mc1120.events.CommonEventHandler.registerRecipes(CommonEventHandler.java:60)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_645_CommonEventHandler_registerRecipes_Register.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.registries.GameData.redirect$zzj000$_supermartijn642corelib_1_1_12a_forge_mc1_12$fireRegistryEventsRedirectPost(GameData.java:1515)
    at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:857)
    at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:636)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:747)
    at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:108)
    at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:338)
    at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:219)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
    at java.lang.Thread.run(Unknown Source)

(MixinBooter) Mixins in Stacktrace:
    net/minecraftforge/fml/common/eventhandler/EventBus:
        com.cleanroommc.groovyscript.core.mixin.EventBusMixin (mixin.groovyscript.json) [groovyscript-0.6.1.jar]
    net/minecraftforge/common/crafting/CraftingHelper:
        com.supermartijn642.core.mixin.CraftingHelperMixin (supermartijn642corelib.mixins.json) [_supermartijn642corelib-1.1.12a-forge-mc1.12.jar]
    net/minecraftforge/fml/common/FMLCommonHandler:
        org.embeddedt.vintagefix.mixin.branding.FMLCommonHandlerMixin (mixins.vintagefix.json) [unknown-source]
        zone.rong.loliasm.common.vanities.mixins.FMLCommonHandlerMixin (mixins.vanities.json) [censoredasm5.14.jar]
    net/minecraft/server/MinecraftServer:
        zone.rong.loliasm.common.priorities.mixins.MinecraftServerMixin (mixins.priorities.json) [censoredasm5.14.jar]
        mod.acgaming.universaltweaks.tweaks.world.loading.mixin.UTInitialChunkLoadMixin (mixins.tweaks.world.loading.server.json) [UniversalTweaks-1.12.2-1.8.0.jar]
    net/minecraftforge/registries/GameData:
        org.dimdev.jeid.mixin.core.MixinGameData (mixins.jeid.core.json) [RoughlyEnoughIDs-2.0.6.jar]
        com.supermartijn642.core.mixin.GameDataMixin (supermartijn642corelib.mixins.json) [_supermartijn642corelib-1.1.12a-forge-mc1.12.jar]
        mod.acgaming.universaltweaks.tweaks.performance.prefixcheck.mixin.UTPrefixCheckMixin (mixins.tweaks.performance.prefixcheck.json) [UniversalTweaks-1.12.2-1.8.0.jar]
    net/minecraftforge/fml/common/Loader:
        io.github.lxgaming.sledgehammer.mixin.forge.fml.common.LoaderMixin (mixins.sledgehammer.preinit.json) [unknown-source]
    net/minecraft/server/dedicated/DedicatedServer:
        mod.acgaming.universaltweaks.tweaks.misc.difficulty.mixin.UTDefaultDifficultyMPMixin (mixins.tweaks.misc.difficulty.server.json) [UniversalTweaks-1.12.2-1.8.0.jar]
        io.github.lxgaming.sledgehammer.mixin.core.server.DedicatedServerMixin (mixins.sledgehammer.core.json) [unknown-source]
        mod.acgaming.universaltweaks.tweaks.misc.buttons.snooper.mixin.UTSnooperServer (mixins.tweaks.misc.buttons.snooper.server.json) [UniversalTweaks-1.12.2-1.8.0.jar]
    net/minecraft/server/MinecraftServer:
        zone.rong.loliasm.common.priorities.mixins.MinecraftServerMixin (mixins.priorities.json) [censoredasm5.14.jar]
        mod.acgaming.universaltweaks.tweaks.world.loading.mixin.UTInitialChunkLoadMixin (mixins.tweaks.world.loading.server.json) [UniversalTweaks-1.12.2-1.8.0.jar]

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 11 (amd64) version 10.0
  Java Version: 1.8.0_371, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 3569350648 bytes (3403 MB) / 5670699008 bytes (5408 MB) up to 8589934592 bytes (8192 MB)
  JVM Flags: 20 total; -Xms128M -Xmx8192M -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 LoliASM 5.14 VintageFix 0.2.12 Powered by Forge 14.23.5.2860 135 mods loaded, 135 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                       | Version                             | Source                                                      | Signature                                |
       |:----- |:------------------------ |:----------------------------------- |:----------------------------------------------------------- |:---------------------------------------- |
       | LCH   | minecraft                | 1.12.2                              | minecraft.jar                                               | None                                     |
       | LCH   | mcp                      | 9.42                                | minecraft.jar                                               | None                                     |
       | LCH   | bansoukou                | 4.3.1                               | minecraft.jar                                               | None                                     |
       | LCH   | FML                      | 8.0.99.99                           | forge-1.12.2-14.23.5.2860.jar                               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCH   | forge                    | 14.23.5.2860                        | forge-1.12.2-14.23.5.2860.jar                               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCH   | creativecoredummy        | 1.0.0                               | minecraft.jar                                               | None                                     |
       | LCH   | micdoodlecore            | 4.0.5                               | minecraft.jar                                               | None                                     |
       | LCH   | tfg                      | 4.3.2                               | .                                                           | None                                     |
       | LCH   | littletilescore          | 1.0.0                               | minecraft.jar                                               | None                                     |
       | LCH   | mixinbooter              | 8.4                                 | minecraft.jar                                               | None                                     |
       | LCH   | opencomputers|core       | 1.8.3                               | minecraft.jar                                               | None                                     |
       | LCH   | configanytime            | 1.0                                 | !configanytime-1.0.jar                                      | None                                     |
       | LCH   | supermartijn642corelib   | 1.1.12a                             | _supermartijn642corelib-1.1.12a-forge-mc1.12.jar            | None                                     |
       | LCH   | appliedenergistics2      | rv6-stable-7-extended_life-v0.55.21 | appliedenergistics2-rv6-stable-7-extended_life-v0.55.21.jar | None                                     |
       | LCH   | codechickenlib           | 3.2.3.358                           | CodeChickenLib-1.12.2-3.2.3.358-universal.jar               | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCH   | redstoneflux             | 2.1.1                               | RedstoneFlux-1.12-2.1.1.1-universal.jar                     | None                                     |
       | LCH   | brandonscore             | 2.4.20                              | BrandonsCore-1.12.2-2.4.20.162-universal.jar                | None                                     |
       | LCH   | aenetvistool             | 1.0.3                               | AE-Net-Vis-Tool-1.12.2-1.0.3.0-universal.jar                | None                                     |
       | LCH   | forgelin                 | 1.8.4                               | Forgelin-1.8.4.jar                                          | None                                     |
       | LCH   | aeadditions              | 1.3.8                               | AEAdditions-1.12.2-1.3.8.jar                                | None                                     |
       | LCH   | architecturecraft        | @VERSION@                           | architecturecraft-1.12-3.108.jar                            | None                                     |
       | LCH   | astikorcarts             | tfc-1.12.2-0.1.2.9                  | astikorcarts-tfc-1.12.2-0.1.2.9.jar                         | None                                     |
       | LCH   | crafttweaker             | 4.1.20                              | CraftTweaker2-1.12-4.1.20.691.jar                           | None                                     |
       | LCH   | charset                  | 0.5.6.6                             | Charset-Lib-0.5.6.6.jar                                     | None                                     |
       | LCH   | jei                      | 4.25.0                              | HadEnoughItems_1.12.2-4.25.0.jar                            | None                                     |
       | LCH   | athenaeum                | 1.12.2-1.19.6                       | athenaeum-1.12.2-1.19.6.jar                                 | None                                     |
       | LCH   | baubles                  | 1.12.2-1.6.0                        | Baubles-1.12.2-1.0.6.0.jar                                  | None                                     |
       | LCH   | quark                    | r1.6-188                            | QuarkRotN-r1.6-188.jar                                      | None                                     |
       | LCH   | autoreglib               | 1.3-32                              | AutoRegLib-1.3-32.jar                                       | None                                     |
       | LCH   | betterp2p_plusplus       | 1.12.2-1.2.3-extended_life          | betterp2p_plusplus-1.12.2-1.2.3-extended_life.jar           | None                                     |
       | LCH   | modularui                | 2.1.0                               | modularui-2.1.0.jar                                         | None                                     |
       | LCH   | bogosorter               | 1.2.9                               | bogosorter-1.2.9.jar                                        | None                                     |
       | LCH   | bookshelf                | 2.3.590                             | Bookshelf-1.12.2-2.3.590.jar                                | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCH   | buildinggadgets          | 2.8.4                               | BuildingGadgets-2.8.4.jar                                   | None                                     |
       | LCH   | carryon                  | 1.12.3                              | carryon-1.12.2-1.12.7.23.jar                                | None                                     |
       | LCH   | catwalks                 | 1.12.2-4.0.45                       | catwalks-1.12.2-4.0.45.jar                                  | None                                     |
       | LCH   | tfc                      | 1.7.23.181                          | TerraFirmaCraft-MC1.12.2-1.7.23.181-patched.jar             | None                                     |
       | LCH   | cellars                  | 1.24.3                              | CellarAddon-1.24.3.jar                                      | None                                     |
       | LCH   | loliasm                  | 5.14                                | censoredasm5.14.jar                                         | None                                     |
       | LCH   | chisel                   | MC1.12.2-1.0.2.45                   | Chisel-MC1.12.2-1.0.2.45.jar                                | None                                     |
       | LCH   | clumps                   | 3.1.2                               | Clumps-3.1.2.jar                                            | None                                     |
       | LCH   | extendedrenderer         | v1.0                                | coroutil-1.12.1-1.2.37.jar                                  | None                                     |
       | LCH   | coroutil                 | 1.12.1-1.2.37                       | coroutil-1.12.1-1.2.37.jar                                  | None                                     |
       | LCH   | configmod                | v1.0                                | coroutil-1.12.1-1.2.37.jar                                  | None                                     |
       | LCH   | corpse                   | 1.12.2-1.0.8                        | corpse-1.12.2-1.0.8.jar                                     | None                                     |
       | LCH   | craftingtweaks           | 9.0.1                               | CraftingTweaks_1.12.2-9.0.1.jar                             | None                                     |
       | LCH   | crafttweakerjei          | 2.0.3                               | CraftTweaker2-1.12-4.1.20.691.jar                           | None                                     |
       | LCH   | creativecore             | 1.10.0                              | CreativeCore_v1.10.70_mc1.12.2.jar                          | None                                     |
       | LCH   | groovyscript             | 0.6.1                               | groovyscript-0.6.1.jar                                      | None                                     |
       | LCH   | theoneprobe              | 1.4.28                              | theoneprobe-1.12-1.4.28.jar                                 | None                                     |
       | LCH   | gregtech                 | 2.7.3-beta                          | gregtech-1.12.2-2.7.3-beta.jar                              | None                                     |
       | LCH   | devtech                  | 2.1.4                               | devtech-2.1.4.jar                                           | None                                     |
       | LCH   | doubleslabs              | 0.12.2                              | DoubleSlabs-1.12-0.12.2.jar                                 | None                                     |
       | LCH   | dropt                    | 1.12.2-1.19.3                       | dropt-1.12.2-1.19.3.jar                                     | None                                     |
       | LCH   | enderstorage             | 2.4.9                               | EnderStorage-1.12.2-2.4.9.jar                               | None                                     |
       | LCH   | extracpus                | 1.12.2-1.2.1                        | extracpus-1.12.2-1.2.1.jar                                  | None                                     |
       | LCH   | galacticraftcore         | 4.0.5                               | Galacticraft-1.12.2-4.0.5.jar                               | None                                     |
       | LCH   | galacticraftplanets      | 4.0.5                               | Galacticraft-1.12.2-4.0.5.jar                               | None                                     |
       | LCH   | mjrlegendslib            | 1.12.2-1.2.1                        | MJRLegendsLib-1.12.2-1.2.1.jar                              | b02331787272ec3515ebe63ecdeea0d746653468 |
       | LCH   | extraplanets             | 1.12.2-0.7.6                        | ExtraPlanets-1.12.2-0.7.6.jar                               | b02331787272ec3515ebe63ecdeea0d746653468 |
       | LCH   | fasterladderclimbing     | 0.1-146                             | FasterLadderClimbing-1.12-0.1-146.jar                       | None                                     |
       | LCH   | findme                   | 1.0.0                               | findme-1.12.2-1.0.0.jar                                     | None                                     |
       | LCH   | firmalife                | 0.5.1                               | firmalife-0.5.1.jar                                         | None                                     |
       | LCH   | tfcflorae                | 1.4.6                               | TFC-Florae-MC1.12.2-1.4.6.jar                               | None                                     |
       | LCH   | floraefixes              | 1.0                                 | floraefixes-1.0.jar                                         | None                                     |
       | LCH   | ae2fc                    | 2.4.28-r                            | Fluid Craft for AE2-2.4.28-r.jar                            | None                                     |
       | LCH   | forgemultipartcbe        | 2.6.2.83                            | ForgeMultipart-1.12.2-2.6.2.83-universal.jar                | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCH   | microblockcbe            | 2.6.2.83                            | ForgeMultipart-1.12.2-2.6.2.83-universal.jar                | None                                     |
       | LCH   | minecraftmultipartcbe    | 2.6.2.83                            | ForgeMultipart-1.12.2-2.6.2.83-universal.jar                | None                                     |
       | LCH   | ftbbackups               | 1.1.0.1                             | FTBBackups-1.1.0.1.jar                                      | None                                     |
       | LCH   | ftblib                   | 5.4.7.2                             | FTBLib-5.4.7.2.jar                                          | None                                     |
       | LCH   | ftbutilities             | 5.4.1.131                           | FTBUtilities-5.4.1.131.jar                                  | None                                     |
       | LCH   | itemfilters              | 1.0.4.2                             | ItemFilters-1.0.4.2.jar                                     | None                                     |
       | LCH   | ftbquests                | 1202.9.0.15                         | FTBQuests-1202.9.0.15.jar                                   | None                                     |
       | LCH   | opencomputers            | 1.8.3                               | OpenComputers-MC1.12.2-1.8.3+274990f.jar                    | None                                     |
       | LCH   | galacticcomputers        | 1.0.0                               | GalacticComputers-1.0.0.jar                                 | None                                     |
       | LCH   | galacticresearch         | 1.0.0                               | GalacticResearch-1.0.6.jar                                  | None                                     |
       | LCH   | grandeconomy             | 2.1.2                               | GrandEconomy-1.12.2-2.1.2.jar                               | None                                     |
       | LCH   | gcym                     | 1.2.5                               | GregicalityMultiblocks-1.2.5.jar                            | None                                     |
       | LCH   | gregtechfoodoption       | @VERSION@                           | gregtechfoodoption-1.9.3.1.jar                              | None                                     |
       | LCH   | hgp                      | Release                             | hgp-1.0.jar                                                 | None                                     |
       | LCH   | horsepower               | 2.6.7-TFC                           | HorsePowerTFC-MC1.12.2-2.6.7.jar                            | None                                     |
       | LCH   | tfgmod                   | @VERSION@                           | tfgmod-2.0.18.jar                                           | None                                     |
       | LCH   | hotornot                 | 1.7                                 | hotornot-1.7.jar                                            | None                                     |
       | LCH   | inworldcrafting          | 1.12.2-1.2.0                        | inworldcrafting-1.12.2-1.2.0-universal.jar                  | None                                     |
       | LCH   | journeymap               | 1.12.2-5.7.1                        | journeymap-1.12.2-5.7.1.jar                                 | None                                     |
       | LCH   | jecalculation            | 1.12.2-3.2.7                        | JustEnoughCalculation-1.12.2-3.2.7.jar                      | None                                     |
       | LCH   | littletiles              | 1.5.0                               | LittleTiles_v1.5.80_mc1.12.2.jar                            | None                                     |
       | LCH   | loottweaker              | 0.3.1                               | LootTweaker-0.3.1+MC1.12.2.jar                              | None                                     |
       | LCH   | supermartijn642configlib | 1.1.6                               | supermartijn642configlib-1.1.7-forge-mc1.12.jar             | None                                     |
       | LCH   | movingelevators          | 1.4.3                               | movingelevators-1.4.3-forge-mc1.12.jar                      | None                                     |
       | LCH   | mrtjpcore                | 2.1.4.43                            | MrTJPCore-1.12.2-2.1.4.43-universal.jar                     | None                                     |
       | LCH   | mtlib                    | 3.0.7                               | MTLib-3.0.7.jar                                             | None                                     |
       | LCH   | nae2                     | 1.3.0                               | nae2-1.3.0.jar                                              | None                                     |
       | LCH   | neenergistics            | @VERSION@                           | NotEnoughEnergistics-1.12.2-2.0.6.jar                       | None                                     |
       | LCH   | hbm                      | NTM-Extended-1.12.2-1.9.7           | NTM-Extended-1.12.2-1.9.7.jar                               | None                                     |
       | LCH   | oxygen_core              | 0.11.4                              | oxygen-core-1.12.2-0.11.4.jar                               | bd38448c93e077d9ef82cf9509ae67b404862367 |
       | LCH   | oxygen_cp_ge             | 0.11.1                              | oxygen-cp-grand-economy-1.12.2-0.11.2.jar                   | e48bc44997dd6e7539e0c065b588c11fbdd1f650 |
       | LCH   | oxygen_exchange          | 0.11.1                              | oxygen-exchange-1.12.2-0.11.1.jar                           | bd38448c93e077d9ef82cf9509ae67b404862367 |
       | LCH   | oxygen_mail              | 0.11.2                              | oxygen-mail-1.12.2-0.11.2.jar                               | bd38448c93e077d9ef82cf9509ae67b404862367 |
       | LCH   | oxygen_market            | 0.11.2                              | oxygen-market-1.12.2-0.11.2.jar                             | bd38448c93e077d9ef82cf9509ae67b404862367 |
       | LCH   | oxygen_shop              | 0.11.1                              | oxygen-shop-1.12.2-0.11.1.jar                               | bd38448c93e077d9ef82cf9509ae67b404862367 |
       | LCH   | oxygen_teleportation     | 0.11.1                              | oxygen-teleportation-1.12.2-0.11.1.jar                      | bd38448c93e077d9ef82cf9509ae67b404862367 |
       | LCH   | p455w0rdslib             | 2.3.161                             | p455w0rdslib-1.12.2-2.3.161.jar                             | 186bc454cd122c9c2f1aa4f95611254bcc543363 |
       | LCH   | performant               | 1.12.2-1.5                          | performant-1.11.jar                                         | None                                     |
       | LCH   | placebo                  | 1.6.0                               | Placebo-1.12.2-1.6.1.jar                                    | None                                     |
       | LCH   | projectred-core          | 4.9.4.120                           | ProjectRed-1.12.2-4.9.4.120-Base.jar                        | None                                     |
       | LCH   | projectred-integration   | 4.9.4.120                           | ProjectRed-1.12.2-4.9.4.120-integration.jar                 | None                                     |
       | LCH   | projectred-transmission  | 4.9.4.120                           | ProjectRed-1.12.2-4.9.4.120-integration.jar                 | None                                     |
       | LCH   | projectred-fabrication   | 4.9.4.120                           | ProjectRed-1.12.2-4.9.4.120-fabrication.jar                 | None                                     |
       | LCH   | projectred-illumination  | 4.9.4.120                           | ProjectRed-1.12.2-4.9.4.120-lighting.jar                    | None                                     |
       | LCH   | puddles                  | 1.1                                 | Puddles-1.1.jar                                             | None                                     |
       | LCH   | jeid                     | 2.0.6                               | RoughlyEnoughIDs-2.0.6.jar                                  | None                                     |
       | LCH   | sinkorswim               | 1.0.0                               | Sink-1.0.0.jar                                              | None                                     |
       | LCH   | sledgehammer             | 1.12.2-2.0.23                       | Sledgehammer-1.12.2-2.0.23.jar                              | None                                     |
       | LCH   | spatialservermod         | 1.3.1                               | spatialservermod-1.3.1.jar                                  | None                                     |
       | LCH   | sasit                    | 1.1.32                              | StuffASockInIt-1.12.2-1.1.32.jar                            | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCH   | tfcthings                | 1.3.5                               | terrafirmathings-1.3.5.jar                                  | None                                     |
       | LCH   | aged_drinks              | 1.0.1                               | TFCAgedDrinks-1.0.7.jar                                     | None                                     |
       | LCH   | tfcalloycalc             | 1.0                                 | TFCAlloyCalc-1.0.jar                                        | None                                     |
       | LCH   | tfcambiental             | 2.1                                 | tfcambiental-2.3.jar                                        | None                                     |
       | LCH   | tfcmedicinal             | 1.0.0                               | TFCMedicinal-1.0.6.jar                                      | None                                     |
       | LCH   | tfctech                  | 1.2.16                              | TFCTech-Unofficial-MC1.12.2-1.2.16.jar                      | None                                     |
       | LCH   | thah                     | 1.2.0                               | thah-1.2.0.jar                                              | None                                     |
       | LCH   | toolbelt                 | 1.9.14                              | ToolBelt-1.12.2-1.9.14.jar                                  | None                                     |
       | LCH   | topaddons                | 1.12.2-1.13.0                       | topaddons-1.12.2-1.13.0.jar                                 | None                                     |
       | LCH   | topextras                | 1.0.1                               | topextras-1.12.2-1.0.1.jar                                  | None                                     |
       | LCH   | travelersbackpack        | 1.0.35                              | TravelersBackpack-1.12.2-1.0.35.jar                         | None                                     |
       | LCH   | treechop                 | 0.14.6                              | TreeChop-1.12.2-0.14.7.jar                                  | None                                     |
       | LCH   | universaltweaks          | 1.12.2-1.8.0                        | UniversalTweaks-1.12.2-1.8.0.jar                            | None                                     |
       | LCH   | vintagefix               | 0.2.12                              | vintagefix-0.2.12.jar                                       | None                                     |
       | LCH   | waterflasks              | 1.9                                 | waterflasks-1.9.jar                                         | None                                     |
       | LCH   | weather2remaster         | 2.8.5.7-alpha                       | Weather2Remastered-1.12.2-2.8.5.7-alpha.jar                 | None                                     |
       | LCH   | xtones                   | 1.2.2                               | Xtones-1.2.2.jar                                            | None                                     |
       | LCH   | orelib                   | 3.6.0.1                             | OreLib-1.12.2-3.6.0.1.jar                                   | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
  Loaded coremods (and transformers): -Bansoukou- (_bansoukou-4.3.1.jar)
                                        
                                      NEELoadingPlugin (NotEnoughEnergistics-1.12.2-2.0.6.jar)
                                        com.github.vfyjxf.nee.asm.NEEClassTransformer
                                      ReflectorsPlugin (GalacticResearch-1.0.6.jar)
                                        igentuman.galacticresearch.reflection.ReflectorsPlugin
                                      UniversalTweaksCore (UniversalTweaks-1.12.2-1.8.0.jar)
                                        
                                      GregTechLoadingPlugin (gregtech-1.12.2-2.7.3-beta.jar)
                                        gregtech.asm.GregTechTransformer
                                      LoliASM (censoredasm5.14.jar)
                                        
                                      JeiUtilitiesLoadingPlugin (JEI-Utilities-1.12.2-0.2.12.jar)
                                        com.github.vfyjxf.jeiutilities.asm.JeiUtilitiesClassTransformer
                                      ModularUI-Core (modularui-2.1.0.jar)
                                        
                                      NAE2-Core (nae2-1.3.0.jar)
                                        
                                      VintageFix (vintagefix-0.2.12.jar)
                                        
                                      Moving Elevators Plugin (movingelevators-1.4.3-forge-mc1.12.jar)
                                        
                                      AE2ELCore (appliedenergistics2-rv6-stable-7-extended_life-v0.55.21.jar)
                                        appeng.core.transformer.AE2ELTransformer
                                      Players List Core Plugin (oxygen-players-list-1.12.2-0.11.1.jar)
                                        austeretony.oxygen_playerslist.common.core.PlayersListClassTransformer
                                      ForgelinPlugin (Forgelin-1.8.4.jar)
                                        
                                      CreativePatchingLoader (CreativeCore_v1.10.70_mc1.12.2.jar)
                                        
                                      Quark Plugin (QuarkRotN-r1.6-188.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      FluidCraftCore (Fluid Craft for AE2-2.4.28-r.jar)
                                        com.glodblock.github.coremod.FCClassTransformer
                                      CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      MixinBooter (!mixinbooter-8.4.jar)
                                        
                                      BogoSorter-Core (bogosorter-1.2.9.jar)
                                        
                                      SuperMartijn642's Core Lib Plugin (_supermartijn642corelib-1.1.12a-forge-mc1.12.jar)
                                        
                                      GroovyScript-Core (groovyscript-0.6.1.jar)
                                        
                                      LittlePatchingLoader (LittleTiles_v1.5.80_mc1.12.2.jar)
                                        com.creativemd.littletiles.LittleTilesTransformer
                                      DoubleSlabs Plugin (DoubleSlabs-1.12-0.12.2.jar)
                                        cjminecraft.doubleslabs.client.asm.ClassTransformer
                                      TransformerLoader (OpenComputers-MC1.12.2-1.8.3+274990f.jar)
                                        li.cil.oc.common.asm.ClassTransformer
                                      JustEnoughIDs Extension Plugin (RoughlyEnoughIDs-2.0.6.jar)
                                        org.dimdev.jeid.JEIDTransformer
                                      ConfigAnytimePlugin (!configanytime-1.0.jar)
                                        
                                      MicdoodlePlugin (Galacticraft-1.12.2-4.0.5.jar)
                                        micdoodle8.mods.miccore.MicdoodleTransformer
  AE2 Version: stable rv6-stable-7-extended_life-v0.55.21 for Forge 14.23.5.2847
  Suspected Mods: DoubleSlabs (doubleslabs), CraftTweaker2 (crafttweaker), CraftTweaker JEI Support (crafttweakerjei), Forge Mod Loader (FML), Minecraft Forge (forge)
  Profiler Position: N/A (disabled)
  Is Modded: Definitely; Server brand changed to 'fml,forge'
  Type: Dedicated Server (map_server.txt)

```

**Comment by Desoroxxx** [comment]
Having this same issue on a Dedicated Server

**Comment by D3nnis3n** [comment]
Can confirm, more info there: https://github.com/CraftTweaker/CraftTweaker/issues/1781

DoubleSlabs 0.10.0 does seem to work, however.
