### ISSUE TITLE
Crash when joining world.

### ISSUE THREAD

**Issue by phlane** [CJMinecraft01/DoubleSlabs#51]
Here is the description of the crash. I am not sure what other information to give, I know this is lacking.

Description: Exception ticking world

java.lang.NullPointerException: Exception ticking world
	at cjminecraft.doubleslabs.blocks.BlockDoubleSlab.lambda$canCreatureSpawn$34(BlockDoubleSlab.java:454) ~[?:2.4.5] {re:classloading}
	at cjminecraft.doubleslabs.blocks.BlockDoubleSlab$$Lambda$15199/534338757.apply(Unknown Source) ~[?:?] {}
	at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_51] {}
	at cjminecraft.doubleslabs.blocks.BlockDoubleSlab.canCreatureSpawn(BlockDoubleSlab.java:454) ~[?:2.4.5] {re:classloading}
	at net.minecraftforge.common.extensions.IForgeBlockState.canCreatureSpawn(IForgeBlockState.java:196) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.world.spawner.WorldEntitySpawner.canSpawnAtBody(WorldEntitySpawner.java:213) ~[?:?] {re:classloading}
	at net.minecraft.entity.EntitySpawnPlacementRegistry$PlacementType.canSpawnAt(EntitySpawnPlacementRegistry.java:161) ~[?:?] {re:classloading,pl:runtime_enum_extender:A}
	at net.minecraft.world.spawner.WorldEntitySpawner.func_209382_a(WorldEntitySpawner.java:196) ~[?:?] {re:classloading}
	at net.minecraft.world.spawner.WorldEntitySpawner.func_226701_a_(WorldEntitySpawner.java:108) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ServerChunkProvider.func_223434_a(SourceFile:406) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:lithium.mixins.json:avoid_allocations.MixinServerChunkProvider,pl:mixin:A}
	at net.minecraft.world.server.ServerChunkProvider$$Lambda$14007/2061369347.accept(Unknown Source) ~[?:?] {}
	at it.unimi.dsi.fastutil.longs.Long2ObjectLinkedOpenHashMap$1.forEach(Long2ObjectLinkedOpenHashMap.java:1661) ~[fastutil-8.2.1.jar:?] {}
	at com.google.common.collect.Iterables$UnmodifiableIterable.forEach(Iterables.java:105) ~[guava-21.0.jar:?] {}
	at net.minecraft.world.server.ServerChunkProvider.func_217220_m(SourceFile:371) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:lithium.mixins.json:avoid_allocations.MixinServerChunkProvider,pl:mixin:A}
	at net.minecraft.world.server.ServerChunkProvider.func_217207_a(SourceFile:340) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:lithium.mixins.json:avoid_allocations.MixinServerChunkProvider,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:313) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:quark:change-sleeping-player-count,xf:fml:quark:add-rave-hook,pl:mixin:APP:lithium.mixins.json:avoid_allocations.MixinServerWorld,pl:mixin:APP:lithium.mixins.json:fast_tick_scheduler.MixinServerWorld,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:849) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:114) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637) [?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

[crash-2020-06-08_00.36.25-server.txt](https://github.com/CJMinecraft01/DoubleSlabs/files/4743868/crash-2020-06-08_00.36.25-server.txt)

**Comment by CJMinecraft01** [comment]
Which slabs were you using when this occurred?

**Comment by CJMinecraft01** [comment]
Can you please check this error is still present in the latest version?

**Comment by CJMinecraft01** [comment]
Closing due to inactivity
