### ISSUE TITLE
Random crash I've never had before

### ISSUE THREAD

**Issue by retrogatling** [CJMinecraft01/DoubleSlabs#65]
I didn't even go near one of the double slabs
java.lang.IllegalArgumentException: Cannot set property EnumProperty{name=type, clazz=class net.minecraft.state.properties.SlabType, values=[top, bottom, double]} as it does not exist in Block{minecraft:air}
	at net.minecraft.state.StateHolder.func_206870_a(SourceFile:104) ~[?:?] {re:classloading}
	at cjminecraft.doubleslabs.client.model.DoubleSlabBakedModel.getQuads(DoubleSlabBakedModel.java:81) ~[?:2.2.0] {re:classloading}
	at net.minecraft.client.renderer.BlockModelRenderer.renderModelSmooth(BlockModelRenderer.java:73) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.renderModelSmooth(ForgeBlockModelRenderer.java:89) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.BlockModelRenderer.renderModel(BlockModelRenderer.java:51) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.BlockRendererDispatcher.renderModel(BlockRendererDispatcher.java:62) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$ChunkRender$RebuildTask.func_228940_a_(ChunkRenderDispatcher.java:527) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$ChunkRender$RebuildTask.func_225618_a_(ChunkRenderDispatcher.java:449) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.lambda$runTask$1(ChunkRenderDispatcher.java:118) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$$Lambda$11888/1855961067.apply(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1624) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.state.StateHolder.func_206870_a(SourceFile:104)
	at cjminecraft.doubleslabs.client.model.DoubleSlabBakedModel.getQuads(DoubleSlabBakedModel.java:81)
	at net.minecraft.client.renderer.BlockModelRenderer.renderModelSmooth(BlockModelRenderer.java:73)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.renderModelSmooth(ForgeBlockModelRenderer.java:89)

-- Block model being tesselated --
Details:
	Block: Block{doubleslabs:double_slab}
	Block location: World: (-182,69,690), Chunk: (at 10,4,2 in -12,43; contains blocks -192,0,688 to -177,255,703), Region: (-1,1; contains chunks -32,32 to -1,63, blocks -512,0,512 to -1,255,1023)
	Using AO: true
Stacktrace:
	at net.minecraft.client.renderer.BlockModelRenderer.renderModel(BlockModelRenderer.java:51)

-- Block being tesselated --
Details:
	Block: Block{doubleslabs:double_slab}
	Block location: World: (-182,69,690), Chunk: (at 10,4,2 in -12,43; contains blocks -192,0,688 to -177,255,703), Region: (-1,1; contains chunks -32,32 to -1,63, blocks -512,0,512 to -1,255,1023)
Stacktrace:
	at net.minecraft.client.renderer.BlockRendererDispatcher.renderModel(BlockRendererDispatcher.java:62)

**Comment by CJMinecraft01** [comment]
Which Minecraft and mod version is this for?

**Comment by retrogatling** [comment]
1.15.2 and 2.6.1

**Comment by retrogatling** [comment]
*2.2.0

**Comment by CJMinecraft01** [comment]
Hi! Please try updating to a newer version as this has most likely been fixed!

**Comment by CJMinecraft01** [comment]
Closing due to inactivity
